version: '3.9'
services:
  api:
    image: copper-protocol/smart-contracts
    build:
      context: ./data
      args:
        - _USER=${USER}
      target: node-smart-contracts
    environment:
      - PORT
    env_file:
      - ./.env
    volumes:
      - ./api:/home/${USER}/app
      - ${HOME}/.ssh:/home/${USER}/.ssh
    working_dir: /home/${USER}/app
  frontend:
    container_name: dopper-protocol-frontend
    image: copper-protocol/smart-contracts
    build:
      context: ./data
      args:
        - _USER=${USER}
      target: node-mev-frontend
    environment:
      - PORT
    env_file:
      - ./.env
    volumes:
      - ./frontend:/home/${USER}/app
    working_dir: /home/${USER}/app

  copper-protocol-smart-contracts-evm:
    image: copper-protocol/smart-contracts
    build:
      context: ./data
      args:
        - _USER=${USER}
      target: node-smart-contracts
    environment:
      - PORT
    env_file:
      - ./.env
    volumes:
      - ./smart-contracts/evm:/home/${USER}/app
    working_dir: /home/${USER}/app