version: "3.6"
services:
  nginx:
    build: ../nginx
    restart: always
    ports:
      - 5880:80
      - 5443:443
    volumes:
      - ../data/etc/letsencrypt:/etc/letsencrypt
    networks:
      - webserver_backend
      - datanet
  certbot:
    image: copper-protocol/certbot
    extends:
      service: certbot
      file: ./config/docker-compsoe.prod.yml
    volumes:
      - ../data/etc/letsencrypt:/etc/letsencrypt
      - ../data/etc/certbot:/etc/certbot
   
networks:
  webserver_backend:
    external: true
    name: coppernetwork_hosting
  datanet:
    external: true
    name: coppernetwork_datanet